branches:
  only:
  - integration-open-prs

sudo: required

services:
  - docker

language: c
compiler:
  - gcc
  - clang
os:
  - linux
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
env:
  - FLB_MEM="-DFLB_JEMALLOC=On"
  - FLB_MEM="-DFLB_JEMALLOC=Off"

before_script:
  # Install Toolchain for ksz9692 (ARM)
  - if [ $TRAVIS_OS_NAME == linux ]; then if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes gcc-multilib > /dev/null; fi; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then wget http://fluentbit.io/ci-toolchains/ksz9692.tar.gz -O /tmp/ksz9692.tar.gz; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then tar -xf /tmp/ksz9692.tar.gz; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then export PATH=$PATH:$PWD/ksz9692/bin/; fi
  # Unpack the sources
  - cd build
  - cmake -DFLB_ALL=On -DFLB_WITHOUT_EXAMPLES=On $FLB_FLUSH $FLB_MEM -DFLB_TESTS_INTERNAL=On ../

script: make
after_script:
  - cd ..
  - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
  # - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=sddmelb/fluent-bit
  - export TAG=$TRAVIS_BRANCH
  - echo $REPO
  - echo $TAG
  - echo $TRAVIS_COMMIT
  # - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker build . -f Dockerfile -t $REPO:$TRAVIS_COMMIT
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
